### ISSUE TITLE
Feature calculate max bucket proportions

### ISSUE THREAD

**Issue by MarvinMat** [Krockema/MATE#65]
IDEA:
- count arriving operations and their durations --> automatically calculate proportions of for max bucket size
- forget operations older than 1 week

IMPLEMENTATION:
- object with dictionary having (string) "Group technology"  and (int) "totalduration"
- new arriving operation --> "totalduration" += operation.duration

**Comment by MarvinMat** [comment]
added in branch feature-lotsize
Next step: update AkkaSim

**Comment by Krockema** [comment]
close #65
